#!/bin/bash
# [3단계] OpenFOAM: 격자 변환 -> 영역 분리 -> 해석
# 사전 조건: 케이스 폴더에 coldplate.msh, constant/caseParams 가 있어야 함
#            OpenFOAM 환경이 로드되어 있어야 함 (예: source /usr/lib/openfoam/openfoam2412/etc/bashrc)
# 병렬 실행: NP=4 ./Allrun
cd "$(dirname "$0")" || exit 1
set -e

rm -rf 0 processor* constant/polyMesh constant/fluid/polyMesh constant/solid/polyMesh log.*

gmshToFoam coldplate.msh                  > log.gmshToFoam 2>&1
splitMeshRegions -cellZones -overwrite    > log.splitMeshRegions 2>&1
for r in fluid solid; do
    checkMesh -region $r                  > log.checkMesh.$r 2>&1 || true
done

mkdir -p 0
cp -r 0.orig/* 0/

NP=${NP:-1}
if [ "$NP" -gt 1 ]; then
    foamDictionary -entry numberOfSubdomains -set "$NP" system/decomposeParDict > /dev/null 2>&1
    for r in fluid solid; do cp system/decomposeParDict system/$r/; done
    decomposePar -allRegions              > log.decomposePar 2>&1
    mpirun -np "$NP" chtMultiRegionSimpleFoam -parallel > log.chtMultiRegionSimpleFoam 2>&1
    reconstructPar -allRegions -latestTime > log.reconstructPar 2>&1
    rm -rf processor*
else
    chtMultiRegionSimpleFoam              > log.chtMultiRegionSimpleFoam 2>&1
fi
echo "SOLVE_OK"
